--- 
title: "Machine Learning Applications"
author: "Simon P. Raymond"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
description: Introduction
link-citations: yes
github-repo: rstudio/bookdown-demo
---

# About Myself

My name is Simon Raymond. I have finished my Third year at Saint Mary’s University in Halifax NS. I currently have not picked a major but i am very interested in Econometrics and Machine learning.

I intend to keep learning Machine Learning techniques outside of a classroom. This is where i will be uploading some of my generic or basic Algorithms and Practices.

Contact: simon.raymond@smu.ca

## Purpose

I want to display a few things 

(1) Show some basic skeletons of how to build machine learning algorithms
(2) Make some more practical applications
(3) Explain key concepts
(4) Keep track of my learning goals


## Notes for public

N/A

## Work in progress

Parts/sections
Equations

Skeletons
Binary Application.
Regression Application
Imbalanced data
Speed Testing

Our own models package free
Multi class Applicationn With real mnist
Parrallel proccesing ways



For myself

git add docs
git commit -m"update"
git push -u origin main

git add .
git commit -m "Fix graph paths"
git push origin main
